spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/phoneshop_night
    username: phoneshop_night
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true